/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vivi-barrios
 */
public class CambioContra extends javax.swing.JFrame {
    private USUARIO usuario;
    
    /**
     * Creates new form CambioContra
     */
    public CambioContra(USUARIO usuario) {
        this.usuario = usuario;
        initComponents();
        setLocationRelativeTo(this);
        String name = usuario.getNombre();
        Nusuario.setText(name);
        
        
    }
    
    private boolean ValidarDatos(){
        if (!contra.getText().matches("(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).{6,10}")){
            JOptionPane.showMessageDialog(this, "La contraseña debe contener: \n"
                    + "Entre 6-10 caracteres \n"
                    + "Al menos una letra Mayuscula \n"
                    + "Al menos una letra Minuscula \n"
                    + "Al menos un numero");
            return false;
        }   
        
        return true;
    }
    
    private void ActualizarArchivo(){
         ArrayList<String> lineas = new ArrayList<>();
    try (BufferedReader reader = new BufferedReader(new FileReader("Usuario.txt"))) {
        String linea;
        while ((linea = reader.readLine()) != null) {
            String[] datos = linea.split(",");
            if (datos.length == 4 && datos[1].equals(usuario.getUsuario())) {
   
                linea = datos[0] + "," + datos[1] + "," + datos[2] + "," + usuario.getPassword();
            }

            lineas.add(linea);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al leer el archivo");
    }


    try (PrintWriter writer = new PrintWriter(new FileWriter("Usuario.txt"))) {
        for (String nuevaLinea : lineas) {
            writer.println(nuevaLinea);
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el archivo");
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contra = new javax.swing.JTextField();
        GUARDAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Nusuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("CAMBIO CONTRASEÑA");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("NUEVA CONTRASEÑA:");

        GUARDAR.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        GUARDAR.setText("GUARDAR");
        GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GUARDARActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("USUARIO:");

        Nusuario.setEditable(false);
        Nusuario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(GUARDAR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(GUARDAR)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GUARDARActionPerformed
        // TODO add your handling code here:
        if (ValidarDatos()){
            String nuevaContraseña = contra.getText(); 

         if (nuevaContraseña != null && !nuevaContraseña.isEmpty()) {
            usuario.setPassword(nuevaContraseña); 

            ActualizarArchivo();
            JOptionPane.showMessageDialog(this, "Contraseña cambiada");
            this.dispose();
         }
        }
    }//GEN-LAST:event_GUARDARActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GUARDAR;
    private javax.swing.JTextField Nusuario;
    private javax.swing.JTextField contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
