/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author vivi-barrios
 */
public class LOGIN extends javax.swing.JFrame {

    private USUARIO usuario;

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        
        
        initComponents();
        setLocationRelativeTo(this);
       
    }
    
    private void Limpiar (){
        nomUsuario.setText("");
        password.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomUsuario = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Ingresar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        RECUPERACION_CONTRA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("USUARIO:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("PASSWORD:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BIENVENIDO");

        nomUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        password.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N

        Ingresar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        Ingresar.setText("INGRESAR");
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        RECUPERACION_CONTRA.setText("OLVIDE MI CONTRASEÑA");
        RECUPERACION_CONTRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECUPERACION_CONTRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RECUPERACION_CONTRA)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nomUsuario)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Ingresar)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(Ingresar)
                .addGap(18, 18, 18)
                .addComponent(RECUPERACION_CONTRA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void cargarDatos (){
        ProyectoFinal.usuario.clear();
        
        USUARIO us = new USUARIO();
        us.setNombre("Admin");
        us.setPassword("Admin");
        us.setUsuario("Admin");
        us.setRol("Administrador");
        
        ProyectoFinal.usuario.add(us);
        
        try (BufferedReader br = new BufferedReader(new FileReader ("Usuario.txt"))){
            String linea;
            while ((linea = br.readLine()) != null) {
            String [] datos = linea.split(",");
            if (datos.length == 4){
                USUARIO u = new USUARIO();
                u.setNombre(datos [0]);
                u.setUsuario(datos [1]);
                u.setRol(datos [2]);
                u.setPassword(datos [3]);
                
                ProyectoFinal.usuario.add(u);
            }
        }
        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
        }
    }
    
    
    public static void CargarDatosLibrosVentas (){
        ProyectoFinal.CrearVentas.clear();
        ProyectoFinal.librosVentas.clear();
        
        try (BufferedReader br = new BufferedReader(new FileReader ("LibrosVentas.txt"))){
            String linea;
            while ((linea = br.readLine()) != null) {
            String [] datos = linea.split(",");
            if (datos.length == 5){
                L_VENTAS li = new L_VENTAS();
                li.setTitulo(datos [0]);
                li.setAutor(datos [1]);
                li.setGenero(datos [2]);
                li.setPrecio(Double.parseDouble(datos [3]));
                li.setCantidad(datos [4]);
                
                ProyectoFinal.librosVentas.add(li);
            }
        }
        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Libro no encontrado");
        }
    }
        
    public static void CargarDatosCupones(){
        ProyectoFinal.cupones.clear();
        
        try(BufferedReader br = new BufferedReader(new FileReader ("Cupones.txt"))){
            String linea;
            while ((linea = br.readLine()) != null){
            String [] datos = linea.split(","); 
            if (datos.length == 4){
                CUPONES c = new CUPONES();
                c.setCodigoDescuento(datos [0]);
                c.setDescuento(datos [1]);
                c.setTipoDescuento(datos [2]);
                c.setVencimiento(datos [3]);
                
                ProyectoFinal.cupones.add(c);
            }
        }
            
        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Libro no encontrado");
        }
        
    }
    
    public static void CargarDatosTel(){
        ProyectoFinal.telefonos.clear();
        
        try(BufferedReader br = new BufferedReader(new FileReader ("Telefono.txt"))){
            String linea;
            while ((linea = br.readLine()) != null){
            String [] datos = linea.split(","); 
            if (datos.length == 2){
                TELEFONO t = new TELEFONO();
                t.setCodigo(datos [0]);
                t.setNumero(datos [1]);
                
                ProyectoFinal.telefonos.add(t);
            }
        }
            
        }catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Telefono no encontrado");
        }
    }
    
    public USUARIO UsuarioPrincipal() {
        String usuarios = nomUsuario.getText();
    
        if (usuarios.equals("Admin")){
            JOptionPane.showMessageDialog(this, "Al Administrador no "
                    + "se le puede cambiar contraseña");
            return null;
        } else { 
          for (USUARIO u : ProyectoFinal.usuario) {
        if (u.getUsuario().equals(usuarios)) {
            return u;  
        }
          }
    }
    return null;   
        
    }
    
    
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        // TODO add your handling code here:
        CargarDatosTel();
        CargarDatosCupones();
        CargarDatosLibrosVentas();
        cargarDatos();
        
        
        String usua = nomUsuario.getText();
        String contra = password.getText();
        
        boolean existe = false;
        
        for (USUARIO u : ProyectoFinal.usuario){
            if (u.getUsuario().equals(usua) && u.getPassword().equals(contra)){
         
            existe = true; 
            
            ProyectoFinal.usuarios = u;
            
            if (u.getRol().equals("Vendedor")) {
                String nombreVendedor = u.getNombre();
                ProyectoFinal.nombreVendedor = nombreVendedor; 
            }
            
            if (u.getRol().equals("Administrador")){
                
                Vent_Admon v = new Vent_Admon(u);
                v.setVisible(true);
            } else {
                Vent_Vendedor v = new Vent_Vendedor(u);
                
                v.setVisible(true);
            } 
            break;
        }  
        }
           if (existe == false){
            JOptionPane.showMessageDialog(this, "Usuario o Contraseña Incorrecto");
           
        }
         Limpiar();
    }//GEN-LAST:event_IngresarActionPerformed

    private void RECUPERACION_CONTRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECUPERACION_CONTRAActionPerformed
        // TODO add your handling code here:
        USUARIO usuarioP = UsuarioPrincipal(); 
        if (usuarioP != null) {
        
        CambioContra c = new CambioContra(usuarioP);
        c.setVisible(true);  
        } else {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_RECUPERACION_CONTRAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton RECUPERACION_CONTRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nomUsuario;
    private javax.swing.JTextField password;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
