/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

/**
 *
 * @author vivi-barrios
 */
public class Vent_Admon extends javax.swing.JFrame {
    private USUARIO usuario;
    /**
     * Creates new form Vent_Admon
     */
    public Vent_Admon(USUARIO usuario) {
        initComponents();
        setLocationRelativeTo(this);
        String saludar = usuario.getNombre();
        saludo.setText(saludar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        CREAR = new javax.swing.JButton();
        REGRESAR = new javax.swing.JButton();
        CREA_CUPON = new javax.swing.JButton();
        CREAR_TEL = new javax.swing.JButton();
        saludo = new javax.swing.JLabel();
        LIBRO_STOCK = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        CONSUSU = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        CONSLIB = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        CONS_CUPONES = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        CONS_VENTAS = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO ADMINISTRADOR");

        CREAR.setText("CREAR USUARIO");
        CREAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARActionPerformed(evt);
            }
        });

        REGRESAR.setText("REGRESAR");
        REGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGRESARActionPerformed(evt);
            }
        });

        CREA_CUPON.setText("CREAR CUPON");
        CREA_CUPON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREA_CUPONActionPerformed(evt);
            }
        });

        CREAR_TEL.setText("CREAR TELEFONO");
        CREAR_TEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREAR_TELActionPerformed(evt);
            }
        });

        saludo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        saludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LIBRO_STOCK.setText("CREAR LIBRO STOCK");
        LIBRO_STOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIBRO_STOCKActionPerformed(evt);
            }
        });

        jMenu3.setText("USUARIOS");
        jMenu3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        CONSUSU.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CONSUSU.setText("CONSULTAS");
        CONSUSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSUSUActionPerformed(evt);
            }
        });
        jMenu3.add(CONSUSU);

        jMenuBar2.add(jMenu3);

        jMenu5.setText("LIBROS");
        jMenu5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        CONSLIB.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CONSLIB.setText("CONSULTAS");
        CONSLIB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSLIBActionPerformed(evt);
            }
        });
        jMenu5.add(CONSLIB);

        jMenuBar2.add(jMenu5);

        jMenu4.setText("CUPONES");
        jMenu4.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        CONS_CUPONES.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CONS_CUPONES.setText("CONSULTAS");
        CONS_CUPONES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONS_CUPONESActionPerformed(evt);
            }
        });
        jMenu4.add(CONS_CUPONES);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("VENTAS");
        jMenu6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N

        CONS_VENTAS.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        CONS_VENTAS.setText("CONSULTAS");
        CONS_VENTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONS_VENTASActionPerformed(evt);
            }
        });
        jMenu6.add(CONS_VENTAS);

        jMenuBar2.add(jMenu6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CREAR_TEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CREA_CUPON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CREAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(REGRESAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LIBRO_STOCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(LIBRO_STOCK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CREAR_TEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CREA_CUPON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CREAR)
                .addGap(18, 18, 18)
                .addComponent(REGRESAR)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARActionPerformed
        // TODO add your handling code here:
       Crear_Usuario u = new Crear_Usuario();
       u.setVisible(true);
    }//GEN-LAST:event_CREARActionPerformed

    private void REGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGRESARActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_REGRESARActionPerformed

    private void CONSUSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSUSUActionPerformed
        // TODO add your handling code here:
        ConsultaUsuarios c = new ConsultaUsuarios();
        c.setVisible(true);
    }//GEN-LAST:event_CONSUSUActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void CONSLIBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSLIBActionPerformed
        // TODO add your handling code here:
        ConsultaLibros a = new ConsultaLibros();
        a.setVisible(true);
    }//GEN-LAST:event_CONSLIBActionPerformed

    private void CONS_CUPONESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONS_CUPONESActionPerformed
        // TODO add your handling code here:
        ConsultaCupones c = new ConsultaCupones();
        c.setVisible(true);
        
    }//GEN-LAST:event_CONS_CUPONESActionPerformed

    private void CREA_CUPONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREA_CUPONActionPerformed
        // TODO add your handling code here:
        CrearCupones c = new CrearCupones();
        c.setVisible(true);
    }//GEN-LAST:event_CREA_CUPONActionPerformed

    private void CREAR_TELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREAR_TELActionPerformed
        // TODO add your handling code here:
        CrearTelefonos c = new CrearTelefonos(usuario);
        c.setVisible(true);
    }//GEN-LAST:event_CREAR_TELActionPerformed

    private void CONS_VENTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONS_VENTASActionPerformed
        // TODO add your handling code here:
        ConsultaVentas c = new ConsultaVentas();
        c.setVisible(true);
    }//GEN-LAST:event_CONS_VENTASActionPerformed

    private void LIBRO_STOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIBRO_STOCKActionPerformed
        // TODO add your handling code here:
        CrearLibrosVentas c = new CrearLibrosVentas();
        c.setVisible(true);
    }//GEN-LAST:event_LIBRO_STOCKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CONSLIB;
    private javax.swing.JMenuItem CONSUSU;
    private javax.swing.JMenuItem CONS_CUPONES;
    private javax.swing.JMenuItem CONS_VENTAS;
    private javax.swing.JButton CREAR;
    private javax.swing.JButton CREAR_TEL;
    private javax.swing.JButton CREA_CUPON;
    private javax.swing.JButton LIBRO_STOCK;
    private javax.swing.JButton REGRESAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
}
