    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

import javax.swing.JOptionPane;



/**
 *
 * @author vivi-barrios
 */
public class Vent_Vendedor extends javax.swing.JFrame {
    private USUARIO usuario;

    /**
     * Creates new form Vent_Vendedor
     */
    public Vent_Vendedor(USUARIO usuario) {
        initComponents();
        setLocationRelativeTo(this);
        String saludo = usuario.getNombre();
        saludar.setText(saludo);
    }

     public USUARIO UsuarioPrincipal(USUARIO usuario) {
        String usuarios = usuario.getNombre();
    
        if (usuarios.equals("Admin")){
            JOptionPane.showMessageDialog(this, "Al Administrador no "
                    + "se le puede cambiar contraseña");
            return null;
        } else { 
          for (USUARIO u : ProyectoFinal.usuario) {
        if (u.getUsuario().equals(usuarios)) {
            return u;  
        }
          }
    }
    return null;   
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        saludar = new javax.swing.JLabel();
        SALIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LIBRO_STOCK = new javax.swing.JButton();
        AGREGAR_VENTA = new javax.swing.JButton();
        CAMBIO_CONTRA = new javax.swing.JButton();
        DIRECCION = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saludar.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        saludar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        SALIR.setText("SALIR");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO VENDEDOR");

        LIBRO_STOCK.setText("CREAR LIBRO STOCK");
        LIBRO_STOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIBRO_STOCKActionPerformed(evt);
            }
        });

        AGREGAR_VENTA.setText("AGREGAR VENTA");
        AGREGAR_VENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGREGAR_VENTAActionPerformed(evt);
            }
        });

        CAMBIO_CONTRA.setText("CAMBIO CONTRASEÑA");
        CAMBIO_CONTRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMBIO_CONTRAActionPerformed(evt);
            }
        });

        DIRECCION.setText("AGREGAR DIRECCIONES");
        DIRECCION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIRECCIONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saludar, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(517, 517, 517)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LIBRO_STOCK, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SALIR)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AGREGAR_VENTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CAMBIO_CONTRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DIRECCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saludar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(DIRECCION)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CAMBIO_CONTRA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AGREGAR_VENTA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LIBRO_STOCK)
                .addGap(18, 18, 18)
                .addComponent(SALIR)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_SALIRActionPerformed

    private void LIBRO_STOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIBRO_STOCKActionPerformed
        // TODO add your handling code here:
        CrearLibrosVentas c = new CrearLibrosVentas();
        c.setVisible(true);
    }//GEN-LAST:event_LIBRO_STOCKActionPerformed

    private void AGREGAR_VENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGREGAR_VENTAActionPerformed
        // TODO add your handling code here:
        CrearVentasStock c = new CrearVentasStock();
        c.setVisible(true);
    }//GEN-LAST:event_AGREGAR_VENTAActionPerformed

    private void CAMBIO_CONTRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMBIO_CONTRAActionPerformed
        // TODO add your handling code here:
         USUARIO usuarioP = UsuarioPrincipal(usuario); 
        if (usuarioP != null) {
        
        CambioContra c = new CambioContra(usuarioP);
        c.setVisible(true);  
        } else {
        JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_CAMBIO_CONTRAActionPerformed

    private void DIRECCIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIRECCIONActionPerformed
        // TODO add your handling code here:
        DIRECCION d = new DIRECCION();
        d.setVisible(true);     
    }//GEN-LAST:event_DIRECCIONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AGREGAR_VENTA;
    private javax.swing.JButton CAMBIO_CONTRA;
    private javax.swing.JButton DIRECCION;
    private javax.swing.JButton LIBRO_STOCK;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel saludar;
    // End of variables declaration//GEN-END:variables
}
